import { useParams } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useArenaStore } from "@/lib/arenaStore";

const EventProfilePage = () => {
  const { id } = useParams();
  const { data } = useArenaStore();
  const event = data.events.find((item) => item.id === Number(id));
  const bulls = [...data.bulls].slice(0, event?.bullCount ? Math.min(event.bullCount, data.bulls.length) : 4);
  if (!event) return <div className="min-h-screen bg-background flex items-center justify-center text-muted-foreground">Evento não encontrado.</div>;
  return <div className="min-h-screen bg-background"><Header /><main className="pt-20 pb-20"><div className="relative h-[46vh] overflow-hidden"><img src={event.image || "/placeholder.svg"} alt={event.name} className="w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-background via-background/60 to-transparent" /><div className="absolute bottom-0 left-0 right-0 p-8"><div className="container mx-auto"><span className="text-xs uppercase px-3 py-1 rounded bg-primary/90 text-primary-foreground">{event.status}</span><h1 className="text-4xl md:text-5xl font-semibold uppercase text-gradient-gold mt-4">{event.name}</h1><p className="text-muted-foreground mt-3">{event.location} • {event.city}</p></div></div></div><div className="container mx-auto px-4 mt-10 grid lg:grid-cols-[320px_1fr] gap-8"><aside className="bg-card border border-gold rounded-xl p-6"><div className="space-y-3 text-sm"><p><span className="text-muted-foreground">Início:</span> {event.date}</p><p><span className="text-muted-foreground">Fim:</span> {event.dateEnd}</p><p><span className="text-muted-foreground">Local:</span> {event.location}</p><p><span className="text-muted-foreground">Cidade:</span> {event.city}</p><p><span className="text-muted-foreground">Touros previstos:</span> {event.bullCount}</p></div></aside><section className="space-y-6"><div className="bg-card border border-gold rounded-xl p-6"><h2 className="text-2xl font-semibold mb-4">Sobre o evento</h2><p className="text-muted-foreground leading-relaxed">{event.description || "Descrição não cadastrada."}</p></div><div className="bg-card border border-gold rounded-xl p-6"><h2 className="text-2xl font-semibold mb-4">Touros em destaque</h2>{!bulls.length ? <p className="text-muted-foreground">Nenhum touro cadastrado para exibição.</p> : <div className="space-y-3">{bulls.map((bull, i) => <div key={bull.id} className="flex items-center justify-between bg-background rounded-lg border border-gold p-4"><div className="flex items-center gap-3"><span className="text-xl font-bold text-primary w-8">{i + 1}º</span><div><p className="font-semibold uppercase">{bull.name}</p><p className="text-sm text-muted-foreground">{bull.tropeiro}</p></div></div><span className="text-lg font-bold text-primary">{bull.score}</span></div>)}</div>}</div></section></div></main><Footer /></div>;
};

export default EventProfilePage;
